### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by dunnkers** [zeeguu-ecosystem/Distraction-Shield#153]
- [x] #150 Re-initiate the `onBeforeRequest` handler after timeout has been completed.
- [x] #157 Design overhaul.
- [x] #151 Find out a way to block progressive apps. They store their content offline and continuing with an using an api.
- [x] #147 Only count down when actually at the specific tab.

Then, publish 💠

**Comment by dunnkers** [comment]
💠 All done!
